# Release policy uses the upstream CPack component model for both package formats.
set(CPACK_PRE_BUILD_SCRIPTS "${CMAKE_CURRENT_LIST_DIR}/component-dependencies.cmake")
if(CPACK_GENERATOR STREQUAL "DEB")
    set(CPACK_DEB_COMPONENT_INSTALL ON)
    execute_process(COMMAND dpkg --print-architecture OUTPUT_VARIABLE architecture OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "${architecture}")
    set(CPACK_DEBIAN_PACKAGE_BREAKS "${CPACK_PACKAGE_NAME} (<< ${CPACK_PACKAGE_VERSION})")
    set(CPACK_DEBIAN_PACKAGE_REPLACES "${CPACK_PACKAGE_NAME} (<< ${CPACK_PACKAGE_VERSION})")
    if(CPACK_PACKAGE_NAME STREQUAL "snodec")
        set(CPACK_DEBIAN_CORE_PACKAGE_DEPENDS adduser)
        set(CPACK_DEBIAN_CORE_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_LIST_DIR}/debian/postinst")
    endif()
    set(dependency_version "${CPACK_PACKAGE_VERSION}")
else()
    set(CPACK_RPM_COMPONENT_INSTALL ON)
    set(CPACK_RPM_FILE_NAME RPM-DEFAULT)
    set(CPACK_RPM_PACKAGE_LICENSE "LGPL-3.0-or-later AND MIT")
    set(CPACK_RPM_PACKAGE_RELEASE_DIST OFF)
    set(CPACK_RPM_PACKAGE_RELOCATABLE OFF)
    set(CPACK_RPM_INSTALL_WITH_EXEC ON)
    execute_process(COMMAND rpm --eval "%{_arch}" OUTPUT_VARIABLE architecture OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    set(dependency_version "${CPACK_PACKAGE_VERSION}-${CPACK_RPM_PACKAGE_RELEASE}")
    if(CPACK_PACKAGE_NAME STREQUAL "snodec")
        set(CPACK_RPM_CORE_PACKAGE_REQUIRES_POST "shadow-utils, glibc")
        set(CPACK_RPM_CORE_POST_INSTALL_SCRIPT_FILE "${CMAKE_CURRENT_LIST_DIR}/rpm/postinst")
    endif()
endif()

# Full-install names remain dependency-only packages, derived from components.
set(names "${CPACK_PACKAGE_NAME}\n")
set(depends "")
foreach(component IN LISTS CPACK_COMPONENTS_ALL)
    string(TOLOWER "${CPACK_PACKAGE_NAME}-${component}" name)
    string(APPEND names "${name}\n")
    if(CPACK_GENERATOR STREQUAL "DEB")
        list(APPEND depends "${name} (= ${dependency_version})")
    else()
        string(TOUPPER "${component}" upper)
        set(CPACK_RPM_${upper}_PACKAGE_NAME "${name}")
        list(APPEND depends "${name} = ${dependency_version}")
    endif()
endforeach()
list(JOIN depends ", " depends)
file(MAKE_DIRECTORY "${COMPONENT_OUTPUT}")
file(WRITE "${COMPONENT_OUTPUT}/${CPACK_PACKAGE_NAME}.packages" "${names}")
set(meta "${COMPONENT_OUTPUT}/.meta-${CPACK_PACKAGE_NAME}")
if(CPACK_GENERATOR STREQUAL "DEB")
    file(MAKE_DIRECTORY "${meta}/DEBIAN")
    file(WRITE "${meta}/DEBIAN/control"
        "Package: ${CPACK_PACKAGE_NAME}\nVersion: ${CPACK_PACKAGE_VERSION}\nArchitecture: ${architecture}\nMaintainer: ${CPACK_PACKAGE_CONTACT}\nDepends: ${depends}\nDescription: All ${CPACK_PACKAGE_NAME} components\n")
    execute_process(COMMAND dpkg-deb --build --root-owner-group "${meta}"
        "${COMPONENT_OUTPUT}/${CPACK_PACKAGE_NAME}_${CPACK_PACKAGE_VERSION}_${architecture}.deb"
        COMMAND_ERROR_IS_FATAL ANY)
else()
    file(MAKE_DIRECTORY "${meta}")
    file(WRITE "${meta}/meta.spec"
        "Name: ${CPACK_PACKAGE_NAME}\nVersion: ${CPACK_PACKAGE_VERSION}\nRelease: ${CPACK_RPM_PACKAGE_RELEASE}\nSummary: All ${CPACK_PACKAGE_NAME} components\nLicense: ${CPACK_RPM_PACKAGE_LICENSE}\nRequires: ${depends}\n%description\nAll ${CPACK_PACKAGE_NAME} components.\n%files\n")
    execute_process(COMMAND rpmbuild -bb --define "_topdir ${meta}" --define "_rpmdir ${meta}/RPMS" "${meta}/meta.spec" COMMAND_ERROR_IS_FATAL ANY)
    file(GLOB_RECURSE packages "${meta}/RPMS/*.rpm")
    file(COPY ${packages} DESTINATION "${COMPONENT_OUTPUT}")
endif()
file(REMOVE_RECURSE "${meta}")
