# CPack's component declarations describe ownership. Resolve additional sibling
# library dependencies from the staged ELF files, including bundled plugins.
set(binaries "")
foreach(component IN LISTS CPACK_COMPONENTS_ALL)
    file(GLOB_RECURSE files "${CPACK_TEMPORARY_DIRECTORY}/${component}/*")
    foreach(path IN LISTS files)
        if(IS_SYMLINK "${path}")
            continue()
        endif()
        file(READ "${path}" magic LIMIT 4 HEX)
        if(NOT magic STREQUAL "7f454c46")
            continue()
        endif()
        execute_process(COMMAND readelf -d "${path}" OUTPUT_VARIABLE elf
            COMMAND_ERROR_IS_FATAL ANY)
        list(APPEND binaries "${path}")
        set(owner_${path} "${component}")
        string(REGEX MATCHALL "\\(NEEDED\\)[^\n]*\\[[^]]+\\]" needed "${elf}")
        set(needed_${path} "${needed}")
        if(elf MATCHES "\\(SONAME\\)[^\n]*\\[([^]]+)\\]")
            set(provider_${CMAKE_MATCH_1} "${component}")
            get_filename_component(directory "${path}" DIRECTORY)
            list(APPEND CPACK_DEBIAN_PACKAGE_SHLIBDEPS_PRIVATE_DIRS "${directory}")
        endif()
    endforeach()
endforeach()
list(REMOVE_DUPLICATES CPACK_DEBIAN_PACKAGE_SHLIBDEPS_PRIVATE_DIRS)
foreach(path IN LISTS binaries)
    string(TOUPPER "${owner_${path}}" component)
    foreach(entry IN LISTS needed_${path})
        string(REGEX MATCH "\\[([^]]+)\\]" unused "${entry}")
        set(provider "${provider_${CMAKE_MATCH_1}}")
        if(provider AND NOT provider STREQUAL owner_${path})
            list(APPEND CPACK_COMPONENT_${component}_DEPENDS "${provider}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES CPACK_COMPONENT_${component}_DEPENDS)
endforeach()
