# Package the upstream install rules; do not maintain a second file inventory.
set(CPACK_GENERATOR DEB)
set(CPACK_PACKAGE_NAME mqttsuite)
set(CPACK_PACKAGE_VERSION "${VERSION}")
set(CPACK_PACKAGE_CONTACT "Volker Christian <me@vchrist.at>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "MQTTSuite broker, bridge, integrator, client and store")
set(CPACK_PACKAGING_INSTALL_PREFIX /usr)
set(CPACK_INSTALL_CMAKE_PROJECTS "${BUILD};MQTTSuite;ALL;/")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE arm64)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_DEPENDS "snodec (= ${SNODEC_VERSION})")
set(CPACK_STRIP_FILES YES)
include(CPack)
