name: Development distribution packages
on:
  workflow_dispatch:
    inputs:
      snodec_tag:
        description: Existing SNode.C source tag
        required: true
        type: string
      mqttsuite_tag:
        description: Existing MQTTSuite source tag
        required: true
        type: string
permissions:
  contents: write
  actions: read
jobs:
  packages:
    if: github.event_name == 'workflow_dispatch'
    uses: SNodeC/OpenWRT/.github/workflows/packages.yml@refactor/distribution-packages
    with:
      snodec_tag: ${{ inputs.snodec_tag }}
      mqttsuite_tag: ${{ inputs.mqttsuite_tag }}
    secrets: inherit
